# Generated by Django 5.1.7 on 2025-04-07 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystemApp', '0002_discussion_created_at_discussion_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
    ]
