# Generated by Django 5.1.7 on 2025-04-07 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorySystemApp', '0003_rename_body_comment_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='snippet',
        ),
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
